### ISSUE TITLE
How to run in CPU mode only?

### ISSUE THREAD

**Issue by jairaj-mathur** [ZJUFanLab/scNiche#5]
Hi, thank you for making such a great tool

I dont have a GPU in my machine, and thus no CUDA libraries. how can I pass a flag to scniche to not check for cuda libraries? I gewt the error:
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

thank you!

**Comment by ForwardYang98** [comment]
Hi,
You can download the CPU version of PyTorch and DGL on the [PyTorch](https://pytorch.org/get-started/locally/) and [DGL](https://www.dgl.ai/) website.  However, for large datasets (>10,000 cells), we recommend running scNiche using GPU.

**Comment by jairaj-mathur** [comment]
Thank you, this worked!
